server:
  port: 0
spring:
  application:
    name: main-service
  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        format_sql: true
  sql:
    init:
      mode: always
  datasource:
    url: jdbc:postgresql://localhost:6542/main_db
    username: user
    password: password
    driver-class-name: org.postgresql.Driver

stats:
  service:
    enabled: true
    name: stats-service