server:
  port: 0
  error:
    error:
      include-message: always
      include-binding-errors: always
      include-stacktrace: always
      include-exception: true
      debug: true

spring:
  application:
    name: main-service
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: update
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    properties:
      hibernate:
        format_sql: true
  sql:
    init:
      mode: always
  datasource:
    driver-class-name: org.postgresql.Driver
    url: 'jdbc:postgresql://localhost:6542/main_db'
    username: userdb
    password: 12345