services:

  stats-db:
    image: postgres:16.1
    container_name: "stats-db"
    ports:
      - "6541:5432"
    volumes:
      - /var/lib/postgresql/stats
    environment:
      - POSTGRES_DB=stats
      - POSTGRES_USER=userdb
      - POSTGRES_PASSWORD=12345

  main-db:
    image: postgres:16.1
    container_name: "main-db"
    ports:
      - "6542:5432"
    volumes:
      - /var/lib/postgresql/main-service
    environment:
      - POSTGRES_DB=main_db
      - POSTGRES_USER=userdb
      - POSTGRES_PASSWORD=12345
