server:
  port: 0
spring:
  application:
    name: request-service
  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        format_sql: true
  sql:
    init:
      mode: always
  datasource:
    url: jdbc:postgresql://localhost:6544/request_db
    username: user
    password: password
    driver-class-name: org.postgresql.Driver

stats:
  service:
    enabled: true
    name: stats-service
grpc:
  client:
    collector:
      address: 'discovery:///collector'
      enableKeepAlive: true
      keepAliveWithoutCalls: true
      negotiationType: plaintext