server:
  port: 0
spring:
  application:
    name: analyzer
  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        format_sql: true
  sql:
    init:
      mode: always
  datasource:
    url: jdbc:postgresql://localhost:6546/analyzer_db
    username: user
    password: password
    driver-class-name: org.postgresql.Driver

  kafka:
    consumer-user-actions:
      bootstrap-servers: localhost:9092
      key-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      value-deserializer: ru.practicum.kafka.deserializer.UserActionDeserializer
      client-id: user-consumer
      group-id: group-user
      max-poll-records: 100
      fetch-max-bytes: 3072000
      max-partition-fetch-bytes: 307200
      consume-attempts-timeout-ms: 1000
    consumer-events-similarity:
      bootstrap-servers: localhost:9092
      key-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      value-deserializer: ru.practicum.kafka.deserializer.EventSimilarityDeserializer
      client-id: similarity-consumer
      group-id: group-similarity
      max-poll-records: 100
      fetch-max-bytes: 3072000
      max-partition-fetch-bytes: 307200
      consume-attempts-timeout-ms: 1000
    producer:
      bootstrap-servers: localhost:9092
      key-serializer: org.apache.kafka.common.serialization.StringSerializer
      value-serializer: ru.practicum.kafka.serializer.GeneralAvroSerializer
    topics:
      userActionsTopic: stats.user-actions.v1
      eventsSimilarityTopic: stats.events-similarity.v1

grpc:
  analyzer: # <- должно соответствовать значению в @GrpcClient
    address: 'discovery:///analyzer' # адрес gRPC-сервиса
    enableKeepAlive: true
    keepAliveWithoutCalls: true
    negotiationType: plaintext
logging:
  level:
    io.grpc: DEBUG